### ISSUE TITLE
Please add MIUI and Flyme above Android 5.0 support

### ISSUE THREAD

**Issue by xiangtailiang** [markzhai/InterestingTitleBar#1]
When using this titlebar in MIUI and Flyme above Android 5.0， the shadow will not draw and  the status bar can not see clearly.

**Comment by markzhai** [comment]
Thanks for your suggestion, I will add whitelist to MIUI and Flyme later

**Comment by markzhai** [comment]
Thanks for your suggestion, I will add whitelist to MIUI and Flyme later

**Comment by markzhai** [comment]
Thanks for your suggestion, I will add whitelist to MIUI and Flyme later
